#:schema node_modules/wrangler/config-schema.json
name = "auth-js-d1-example"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "db"
database_name = "auth-js-d1-example-database"
database_id = "769e642d-85b6-4916-9b01-406e8ceaf995"